# docker build -f ./DockerFile -t donsagiv/personal_projects:fileSystemManager .

FROM ubuntu
LABEL author="Ari Sagiv"

EXPOSE 22 80 137/udp 138/udp 139 445

ENV USER_NAME="admin"
ENV USER_PASSWORD="password"
ENV FILE_SYSTEM_DIR="/fsDir"
ENV FILE_SYSTEM_NAME="docker_file_system"

RUN mkdir /init
COPY /init.sh /init/init.sh
RUN groupadd fileSystem

RUN apt update
RUN apt install openssh-server sudo samba -y
RUN rm /etc/samba/smb.conf
COPY /smb.conf /etc/samba/smb.conf

ENTRYPOINT ["/init/init.sh"]